include:
    - project: 'flownative/infrastructure/build-tools'
      file: '/gitlab-ci/docker.base.yaml'
    - project: 'flownative/infrastructure/build-tools'
      file: '/gitlab-ci/docker.build.yaml'
    - project: 'flownative/infrastructure/build-tools'
      file: '/gitlab-ci/docker.release.yaml'
    - project: 'flownative/infrastructure/build-tools'
      file: '/gitlab-ci/docker.release-docker-io.yaml'

variables:
    PROJECT_NAME: 'beach-neos-demo'
    RELEASE_LATEST: 'true'
