Neos:
  Media:
    image:
      defaultOptions:
        # The Vips driver does not support interlace
        interlace: ~

  Imagine:
    driver: 'Vips'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true

