Neos: &settings
  Flow:
    resource:
      storages:
        s3PersistentResourcesStorage:
          storage: 'Flownative\Aws\S3\S3Storage'
            storageOptions:
              bucket: '%env:BEACH_S3_STORAGE_BUCKET%'
              keyPrfix: '/'
      collections:
        persistent:
          storage: 's3PersistentResourcesStorage'
          target: 's3PersistentResourcesTarget'
      targets:
        s3PersistentResourcesTarget:
          target: 'Flownative\Aws\S3\S3Target'
          targetOptions:
            bucket: '%env:BEACH_S3_TARGET_BUCKET%'
            keyPrefix: '/'
            baseUri: '%env:BEACH_PERSISTENT_RESOURCES_BASE_PATH%'

Flownative:
  Aws:
    S3:
      profiles:
        default:
          # Select the API version to use
          version: '2006-03-01'

          # Don't use the old signature v2 - certain regions don't support them
          signature_version: 'v4'

          # Define credentials for authentication
          credentials:
            key: '%env:BEACH_S3_KEY%'
            secret: '%env:BEACH_S3_SECRET%'

          # If the region is not specified, the default region will be used (according to the S3 service)
          region: '%env:BEACH_S3_REGION%'

          # URI Scheme of the base URL (e.g.. 'https', 'http') used when endpoint is not supplied
          scheme: 'https'

          # Custom endpoint, for example for Google Cloud Storage
          endpoint: '%env:BEACH_S3_ENDPOINT%'

          use_path_style_endpoint: true
