Neos:
  Media:
    assetSources:
      'wikipedia_en':
        assetSource: 'DL\AssetSource\MediaWiki\AssetSource\MediaWikiAssetSource'
        assetSourceOptions:
          domain: en.wikipedia.org
          label: Wikipedia (EN)
          searchStrategy: DL\AssetSource\MediaWiki\Api\SearchStrategies\ArticleSearchStrategy
          searchStrategyOptions:
            articleLimit: 10
          useQueryResultCache: true
          excludedIdentifierPatterns:
          - '*.svg'
      'wikipedia_de':
        assetSource: 'DL\AssetSource\MediaWiki\AssetSource\MediaWikiAssetSource'
        assetSourceOptions:
          domain: de.wikipedia.org
          label: Wikipedia (DE)
          searchStrategy: DL\AssetSource\MediaWiki\Api\SearchStrategies\ArticleSearchStrategy
          searchStrategyOptions:
            articleLimit: 10
          useQueryResultCache: true
          excludedIdentifierPatterns:
          - '*.svg'
    image:
      defaultOptions:
        # The Vips driver does not support interlace
        interlace: ~

  Imagine:
    driver: 'Vips'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true

